name: x86-openwrt

on:
  workflow_dispatch:
  schedule:
    - cron: 0 5 1 * * 
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: fetch dependencies
        run: |
          sudo apt update -y
          sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget curl swig rsync
      - name: fetch code
        run: |
          git clone https://github.com/coolsnowwolf/lede.git openwrt/
      - name: copy config
        run: cp config openwrt/.config
      - name: prepare
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig
          make -j8 download V=s
      - name: build
        run: |
          cd openwrt
          make -j$(($(nproc) + 1)) V=s
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          tag: ${{ github.ref }}
          files: bin/*